# Generated by Django 5.1.3 on 2026-06-16 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'created_at'], name='reviews_rev_author__959388_idx'),
        ),
    ]
