# Generated by Django 5.1.3 on 2026-08-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_reviews_rev_author__959388_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_author__959388_idx',
        ),
    ]
